name: restaurant_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  flutter_timezone: ^5.0.0
  http: ^1.5.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  timezone: ^0.10.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.3
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  fonts:
    - family: Gontserrat
      fonts:
        - asset: assets/fonts/Gontserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gontserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gontserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gontserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gontserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Gontserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Gontserrat-Thin.ttf
          weight: 100
